// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineLearningPlatform300.Data;

#nullable disable

namespace OnlineLearningPlatform300.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251025120914_AddMoreCourses")]
    partial class AddMoreCourses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "HyperText Markup Language"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "High Tech Modern Language"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Home Tool Markup Language"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "True"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "False"
                        });
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Web Development",
                            CreatedAt = new DateTime(2025, 10, 25, 17, 39, 13, 855, DateTimeKind.Local).AddTicks(5638),
                            Description = "Master HTML, CSS, JavaScript, React, Node.js, and MongoDB",
                            Duration = 40,
                            ImageUrl = "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
                            Level = "Beginner",
                            Price = 8299m,
                            Title = "Complete Web Development Bootcamp"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Data Science",
                            CreatedAt = new DateTime(2025, 10, 25, 17, 39, 13, 857, DateTimeKind.Local).AddTicks(7282),
                            Description = "Learn Python, pandas, scikit-learn, and TensorFlow",
                            Duration = 35,
                            ImageUrl = "https://images.unsplash.com/photo-1551288049-bebda4e38f71",
                            Level = "Intermediate",
                            Price = 10799m,
                            Title = "Data Science & Machine Learning"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Marketing",
                            CreatedAt = new DateTime(2025, 10, 25, 17, 39, 13, 857, DateTimeKind.Local).AddTicks(7317),
                            Description = "Complete guide to SEO, social media marketing, and Google Ads",
                            Duration = 25,
                            ImageUrl = "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
                            Level = "Beginner",
                            Price = 6599m,
                            Title = "Digital Marketing Mastery"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Mobile Development",
                            CreatedAt = new DateTime(2025, 10, 25, 17, 39, 13, 857, DateTimeKind.Local).AddTicks(7358),
                            Description = "Build cross-platform mobile apps using Flutter and Dart",
                            Duration = 45,
                            ImageUrl = "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c",
                            Level = "Intermediate",
                            Price = 9499m,
                            Title = "Mobile App Development with Flutter"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Cloud Computing",
                            CreatedAt = new DateTime(2025, 10, 25, 17, 39, 13, 857, DateTimeKind.Local).AddTicks(7398),
                            Description = "Master Amazon Web Services and cloud architecture",
                            Duration = 50,
                            ImageUrl = "https://images.unsplash.com/photo-1451187580459-43490279c0fa",
                            Level = "Advanced",
                            Price = 12999m,
                            Title = "Cloud Computing with AWS"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Design",
                            CreatedAt = new DateTime(2025, 10, 25, 17, 39, 13, 857, DateTimeKind.Local).AddTicks(7403),
                            Description = "Learn design principles, Figma, and user experience design",
                            Duration = 30,
                            ImageUrl = "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e",
                            Level = "Beginner",
                            Price = 7299m,
                            Title = "UI/UX Design Fundamentals"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Cybersecurity",
                            CreatedAt = new DateTime(2025, 10, 25, 17, 39, 13, 857, DateTimeKind.Local).AddTicks(7407),
                            Description = "Protect systems and networks from digital attacks",
                            Duration = 38,
                            ImageUrl = "https://images.unsplash.com/photo-1550751827-4bd374c3f58b",
                            Level = "Intermediate",
                            Price = 11499m,
                            Title = "Cybersecurity Essentials"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Blockchain",
                            CreatedAt = new DateTime(2025, 10, 25, 17, 39, 13, 857, DateTimeKind.Local).AddTicks(7412),
                            Description = "Build decentralized applications with Ethereum and Solidity",
                            Duration = 42,
                            ImageUrl = "https://images.unsplash.com/photo-1639762681485-074b7f938ba0",
                            Level = "Advanced",
                            Price = 13799m,
                            Title = "Blockchain Development"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Artificial Intelligence",
                            CreatedAt = new DateTime(2025, 10, 25, 17, 39, 13, 857, DateTimeKind.Local).AddTicks(7416),
                            Description = "Deep learning, neural networks, and AI applications",
                            Duration = 55,
                            ImageUrl = "https://images.unsplash.com/photo-1677442136019-21780ecad995",
                            Level = "Advanced",
                            Price = 14999m,
                            Title = "Artificial Intelligence with Python"
                        },
                        new
                        {
                            Id = 10,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 10, 25, 17, 39, 13, 857, DateTimeKind.Local).AddTicks(7420),
                            Description = "Automate deployment with Docker, Kubernetes, and Jenkins",
                            Duration = 40,
                            ImageUrl = "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb",
                            Level = "Intermediate",
                            Price = 10299m,
                            Title = "DevOps and CI/CD Pipeline"
                        });
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Learn the basics of HTML structure and elements",
                            CourseId = 1,
                            Duration = 15,
                            Order = 1,
                            Title = "Introduction to HTML",
                            Type = 1,
                            VideoUrl = "https://example.com/video1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Understanding CSS selectors, properties, and styling",
                            CourseId = 1,
                            Duration = 20,
                            Order = 2,
                            Title = "CSS Fundamentals",
                            Type = 1,
                            VideoUrl = "https://example.com/video2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Test your knowledge of HTML and CSS",
                            CourseId = 1,
                            Duration = 10,
                            Order = 3,
                            Title = "HTML & CSS Quiz",
                            Type = 2,
                            VideoUrl = ""
                        });
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Points = 10,
                            QuizId = 1,
                            Text = "What does HTML stand for?",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Points = 10,
                            QuizId = 1,
                            Text = "CSS is used for styling web pages.",
                            Type = 1
                        });
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("PassingScore")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test your understanding of HTML and CSS basics",
                            LessonId = 3,
                            PassingScore = 70,
                            Title = "HTML & CSS Assessment"
                        });
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Answer", b =>
                {
                    b.HasOne("OnlineLearningPlatform300.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Enrollment", b =>
                {
                    b.HasOne("OnlineLearningPlatform300.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatform300.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Lesson", b =>
                {
                    b.HasOne("OnlineLearningPlatform300.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Question", b =>
                {
                    b.HasOne("OnlineLearningPlatform300.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Quiz", b =>
                {
                    b.HasOne("OnlineLearningPlatform300.Models.Lesson", "Lesson")
                        .WithMany("Quizzes")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.QuizAttempt", b =>
                {
                    b.HasOne("OnlineLearningPlatform300.Models.Quiz", "Quiz")
                        .WithMany("Attempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatform300.Models.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.UserProgress", b =>
                {
                    b.HasOne("OnlineLearningPlatform300.Models.Lesson", "Lesson")
                        .WithMany("UserProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatform300.Models.User", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Lesson", b =>
                {
                    b.Navigation("Quizzes");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.Quiz", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("OnlineLearningPlatform300.Models.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Progresses");

                    b.Navigation("QuizAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
